// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import useLoginStore from "@/store/loginStore";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const fetchUser = useLoginStore((state) => state.fetchUser);

  // useEffect(() => {
  //   fetchUser(); // Fetch the user data on layout mount
  // }, [fetchUser]);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavBar />
        <main >{children}</main> */}

        {/* <UserProvider>
          <NavBar />
          <main>{children}</main>
        </UserProvider> */}
        <>
          <NavBar />
          <main>{children}</main>
        </>
      </body>
    </html>
  );
}
